"""empty message

Revision ID: 045a826d8cec
Revises: 93102e7cae07
Create Date: 2021-08-08 18:33:29.561759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045a826d8cec'
down_revision = '93102e7cae07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'updated')
    # ### end Alembic commands ###
