"""empty message

Revision ID: 1b2e9d859202
Revises: 045a826d8cec
Create Date: 2021-08-08 20:45:19.551054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b2e9d859202'
down_revision = '045a826d8cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'updated')
    op.drop_column('category', 'created')
    op.drop_column('product', 'updated')
    op.drop_column('product', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('category', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column('category', sa.Column('updated', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
