"""empty message

Revision ID: 93102e7cae07
Revises: 
Create Date: 2021-08-08 18:20:32.362306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93102e7cae07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('product', 'category_id')
    op.alter_column('category', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
