"""empty message

Revision ID: d46fcd0a7e52
Revises: 1b2e9d859202
Create Date: 2021-08-15 02:15:01.485631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46fcd0a7e52'
down_revision = '1b2e9d859202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created')
    op.drop_column('category', 'created')
    # ### end Alembic commands ###
